#!/usr/bin/env python3
"""Generate MASTER-RESULTS.md — every run, every number, one document.

Steve's requirement: after a restart, one file answers "what did we measure?"
for every single run — the time, the cost, the TIER score, and the outcome.

Sources, all in-repo and all regenerable:
  */*/*/rep*/result.json   per-run truth (outcome, cost, wall seconds, tokens)
  tier-scores/<task>.json  TIER's own answer, read from a live tierd per task

DIRECTION OF THE TWO SCORE COLUMNS — they point OPPOSITE ways:

    TIER          = points / (total_cost_USD / $1,000)   HIGHER is better
    cost_per_point = total_cost_USD / points             LOWER is better

(engine.go:202 and :209.) Both are printed here, so the header labels the
direction. Reading one with the other's convention inverts the whole table.

NO SCORE vs 0.0 — the one judgement this script makes, and why:

tierd's JSON returns `tier: 0.0, cost_per_point: 0.0` for a developer with spend
and zero accepted outcomes. Printed literally in a LOWER-is-better column, that
developer sorts as the MOST efficient on the board — a value produced by
dividing real spend by zero delivered work. haiku spent $1.5557 on orgsync and
delivered nothing; $0.0000/pt would say it did so for free.

So a cell with zero accepted outcomes prints NO SCORE and its spend is shown
beside it. "No accepted outcome" and "perfectly efficient" are opposite
statements.

The engine already knows this -- engine.go:206-208 guards on the POINTS
denominator deliberately (#239), intending a zero-point row to render as "—".
What is missing is that the intent does not survive JSON serialization: the wire
format emits a literal 0.0, so the convention lives only in a Go comment. Filed
as tier#472. This script must not be the only place it is handled.
"""
import glob
import json
import os
import statistics
from collections import defaultdict

ROOT = os.path.dirname(os.path.abspath(__file__))
TASKS = ["baseline", "cronspec", "orgsync"]
TIER_LABEL = {"baseline": "EASY", "cronspec": "MEDIUM", "orgsync": "INTEGRATION"}


def billed(r):
    """Non-overlapping token total.

    Summing every field of result.json:tokens DOUBLE-COUNTS: input_total
    already contains the cache classes, and cache_w5m/cache_w1h are subsets of
    cache_write. Verified: input_uncached + cache_read + cache_write ==
    input_total exactly.
    """
    t = r.get("tokens") or {}
    return sum(t.get(k, 0) or 0 for k in
               ("input_uncached", "cache_read", "cache_write", "output"))


def main():
    runs = [json.load(open(p)) for p in
            sorted(glob.glob(os.path.join(ROOT, "*/*/*/rep*/result.json")))]
    scores = {}
    for t in TASKS:
        p = os.path.join(ROOT, "tier-scores", f"{t}.json")
        if os.path.exists(p):
            d = json.load(open(p))
            scores[t] = {x["developer"]: x for x in d.get("developers", [])}

    by = defaultdict(list)
    for r in runs:
        by[(r.get("task"), r.get("label"))].append(r)

    out = []
    w = out.append
    w("# MASTER RESULTS — every run, every number\n")
    w("Generated by `master_table.py`. Regenerate any time: `python3 master_table.py`.\n")
    w(f"**{len(runs)} runs** · **${sum(r.get('cost_list_usd') or 0 for r in runs):.4f}** "
      f"at list rates · "
      f"**{sum(1 for r in runs if r.get('outcome') == 'PASS')} PASS / "
      f"{sum(1 for r in runs if r.get('outcome') != 'PASS')} FAIL**\n")
    w("> **NO SCORE is not a low score.** A cell with zero accepted outcomes has no")
    w("> cost-efficiency figure at all — cost without an accepted outcome is not")
    w("> efficiency, it is just spend. The engine guards this deliberately, but the")
    w("> JSON still emits a literal `0.0`, which in a lower-is-better column sorts as")
    w("> the *best* row on the board (tier#472). Rendered here as NO SCORE, with the")
    w("> spend shown beside it.\n")
    w("> **Scores are per task.** There is no combined figure, by construction")
    w("> (PROTOCOL §1). Ranking across difficulty tiers is unsupported.\n")
    w("> **Column directions differ — ↑ means higher is better, ↓ means lower is**")
    w("> **better.** `TIER = points / (cost / $1,000)` so more accepted work per")
    w("> dollar scores higher; `$/point` and `E[$/accepted]` are prices, so lower")
    w("> is better. The best row is therefore the one with the HIGHEST TIER and the")
    w("> LOWEST $/point — on every task here, that is the same model.\n")

    # ---- per-cell summary, one table per task -----------------------------
    for task in TASKS:
        cells = [(m, rs) for (t, m), rs in by.items() if t == task]
        if not cells:
            continue
        w(f"\n## {task} — {TIER_LABEL.get(task, '')}\n")
        w("| model | pass | E[$/accepted] ↓ | total $ | cost disp | mean wall | wall disp | TIER ↑ | $/point ↓ |")
        w("|---|---|---|---|---|---|---|---|---|")
        rows = []
        for m, rs in cells:
            costs = [r["cost_list_usd"] for r in rs if r.get("cost_list_usd") is not None]
            walls = [r["wall_seconds"] for r in rs if r.get("wall_seconds")]
            npass = sum(1 for r in rs if r.get("outcome") == "PASS")
            total = sum(costs)
            exp = total / npass if npass else None
            cd = (100 * statistics.pstdev(costs) / statistics.mean(costs)) if len(costs) > 1 else None
            wd = (100 * statistics.pstdev(walls) / statistics.mean(walls)) if len(walls) > 1 else None
            sc = scores.get(task, {}).get(m)
            # The NO SCORE rule -- see module docstring.
            tier = (f"{sc['tier']:,.1f}" if sc and npass else "**NO SCORE**")
            cpp = (f"${sc['cost_per_point']:.4f}" if sc and npass else "—")
            rows.append((exp if exp is not None else float("inf"), [
                m, f"{npass}/{len(rs)}",
                f"${exp:.4f}" if exp is not None else "**NO SCORE**",
                f"${total:.4f}",
                f"{cd:.1f}%" if cd is not None else "—",
                f"{statistics.mean(walls):.0f}s" if walls else "—",
                f"{wd:.1f}%" if wd is not None else "—",
                tier, cpp]))
        for _, r in sorted(rows, key=lambda x: x[0]):
            w("| " + " | ".join(r) + " |")

    # ---- every single run --------------------------------------------------
    w("\n---\n\n## Every run\n")
    w("| task | model | rep | outcome | cost | wall | billed tokens | own tests | judge |")
    w("|---|---|---|---|---|---|---|---|---|")
    for r in sorted(runs, key=lambda r: (r.get("task") or "", r.get("label") or "",
                                         r.get("rep") or 0)):
        c = r.get("cost_list_usd")
        w("| {} | {} | {} | {} | {} | {} | {:,} | {} | {} |".format(
            r.get("task"), r.get("label"), r.get("rep"),
            "PASS" if r.get("outcome") == "PASS" else f"**{r.get('outcome')}**",
            f"${c:.4f}" if c is not None else "unpriced",
            f"{r.get('wall_seconds')}s" if r.get("wall_seconds") else "—",
            billed(r), r.get("own_tests") or "—", r.get("acceptance") or "—"))

    # ---- provenance --------------------------------------------------------
    w("\n---\n\n## Provenance — what every number can be checked against\n")
    w("| artifact | where |")
    w("|---|---|")
    w("| per-run bundle (log, stamp, prices, submission) | `<tool>/<model>/<task>/rep<N>/` |")
    w("| exact prompt / judge / rate table, by content hash | `evidence/` + `evidence/INDEX.jsonl` |")
    w("| redacted, publishable evidence | `publish/` (`redact.py`) |")
    w("| offline re-derivation of every number | `python3 verify.py publish` |")
    w("| TIER's own scores, per task | `tier-scores/<task>.json` |")
    w("| machine-readable per-run rows | `results.jsonl` / `results.csv` |")
    w("")

    p = os.path.join(ROOT, "MASTER-RESULTS.md")
    open(p, "w").write("\n".join(out) + "\n")
    print(f"wrote {os.path.relpath(p, ROOT)} — {len(runs)} runs, "
          f"{len([1 for t in TASKS if t in scores])} task score sets")


if __name__ == "__main__":
    main()
